version: '3.3'
services:
  server:
    ports:
        - '80:80'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./Frontend-Vuetify/dist:/www
    environment:
      - ASPNETCORE_URLS=http://+:8080 #PORT
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_HOST: 'db'
    ports:
      - '3306:3306'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    
  migration:
    build:
      context: .
      dockerfile: Dockerfile-Migration
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;User ID=user;Password=password;Database=db;SSL Mode=None
    depends_on:
      - db

volumes:
  db-data: