// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UGHApi.DATA;

#nullable disable

namespace UGHApi.Migrations
{
    [DbContext(typeof(Ugh_Context))]
    [Migration("20250723161000_ReplaceAddressSystemWithGeographicLocation")]
    partial class ReplaceAddressSystemWithGeographicLocation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            // This is a placeholder - the actual model will be built by EF
            // when the migration is applied
#pragma warning restore 612, 618
        }
    }
}
