name: Build Docker image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker exec -it urlaubgegenhand systemctl start mysql
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.dockerfile
          push: true
          tags: urlaubgegenhand/urlaubgegenhand:latest
      
