name: Docker-Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-and-push-action@v2
        with:
          # Dockerfile im Repository
          dockerfile: ./Dockerfile
          # Name des Docker-Images
          image: my-image
          # Docker-Repository
          repository: my-docker-repo
